spring:
  h2:
    console:
      enabled: true
    datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true